import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { useTranslations } from "next-intl";
import Navbar from "@/components/header/navbar";
import Footer from "@/components/footer/footer";
import { NavData } from "@/components/type/typdata";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const t = useTranslations("headers");
  const tlang = useTranslations("language");
  const them = useTranslations("theme");

  const navData: NavData = {
    about: t("about"),
    connect: t("connect"),
    tem: t("Team"),
    Trust: t("Trust"),
    Testimonials: t("Testimonials"),
    OurWork: t("OurWork"),
    Ourserver: t("Ourserver"),
    lang: `${locale}`,
    ar: tlang("ar"),
    en: tlang("en"),
    changelag: tlang("change"),
    light: them("light"),
    dark: them("dark"),
    system: them("system"),
  };

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className="bg-gray-50">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar navData={navData} />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
